---
- name: Setup Redhat | Add yum repository
  yum_repository:
    name: td-agent-bit
    description: TD Agent Bit
    baseurl: http://packages.fluentbit.io/centos/7/$basearch/
    gpgcheck: true
    gpgkey: http://packages.fluentbit.io/fluentbit.key
    enabled: true
